### GET ONE POPULATION DATA ENTRY BY CITY & STATE
GET http://127.0.0.1:5555/api/population/state/floridA/city/orlAnde HTTP/1.1

### PUT (UPDATE) ONE POPULATION DATA ENTRY BY CITY & STATE
PUT http://127.0.0.1:5555/api/population/state/Florida/city/Orlande HTTP/1.1
Content-Type: application/json

{
 "population": 2899
}

### POST ONE POPULATION DATA ENTRY BY CITY & STATE
POST http://127.0.0.1:5555/api/population/state/Florida/city/nowherestowne HTTP/1.1
Content-Type: application/json

{
 "population": 1293
}